setwd("/Users/yliu5/Library/CloudStorage/Box-Box/Canlab/publication_2023_version/Figure/Figure3/heatmap_cor_all_level/")
setwd("/Users/yliu5/Downloads/final_submit/figure_code/figure2/")
###similar to shared_gene_v2, but generated by different databases, this one is the same as our supplementary tabe in the paper, feel free to compare them
homo <- read.csv("data/homo_gene_ian.csv",row.names=1)

mean_df_human <- function(df,type,species){
  #colnames(df) <- tolower(colnames(df))
  df_homo <- df[,homo$human]
  tmp <- t(df_homo)
  rownames(tmp)=homo$marker
  df_homo_mean <- data.frame(apply(tmp, 1, mean))
  colnames(df_homo_mean)=paste(species,type,sep="_")
  return(df_homo_mean)
}

mean_df_mouse <- function(df,type,species){
  #colnames(df) <- tolower(colnames(df))
  df_homo <- df[,homo$mouse]
  tmp <- t(df_homo)
  rownames(tmp)=homo$marker
  df_homo_mean <- data.frame(apply(tmp, 1, mean))
  colnames(df_homo_mean)=paste(species,type,sep="_")
  return(df_homo_mean)
}

mean_df_rna_ribo <- function(df,type,species){
  rownames(df) <- tolower(rownames(df))
  df_homo <- df[homo$share_gene,]
  df_homo_mean <- data.frame(apply(df_homo, 1, mean))
  colnames(df_homo_mean)=paste(species,type,sep="_")
  return(df_homo_mean)
}

human_TE <- read.csv("data/human_TE_cellline_all_plain.csv",row.names=1)
mouse_TE <- read.csv("data/mouse_TE_cellline_all_plain.csv",row.names=1)
human_TE_mean <- mean_df_human(human_TE,"TE","Human")
mouse_TE_mean <- mean_df_mouse(mouse_TE,"TE","Mouse")
#load("/Users/yliu5/Library/CloudStorage/Box-Box/CenikLab_Shared/Yue/RiboBase_propotional_data/final_TE_8_2_23/human_flatten_ribo_clr.rda")
#load("/Users/yliu5/Library/CloudStorage/Box-Box/CenikLab_Shared/Yue/RiboBase_propotional_data/final_TE_8_2_23/mouse_flatten_ribo_clr.rda")
human_flatten_ribo_clr <- read.csv("data/human_RIBO_cellline_all_plain.csv",row.names=1)
mouse_flatten_ribo_clr <- read.csv("data/mouse_RIBO_cellline_all_plain.csv",row.names=1)
human_RIBO_mean <- mean_df_human(human_flatten_ribo_clr,"RIBO","Human")
mouse_RIBO_mean <- mean_df_mouse(mouse_flatten_ribo_clr,"RIBO","Mouse")

human_flatten_rna_clr=read.csv("data/human_RNA_cellline_all_plain.csv",row.names=1)
mouse_flatten_rna_clr=read.csv("data/mouse_RNA_cellline_all_plain.csv",row.names=1)
human_RNA_mean <- mean_df_human(human_flatten_rna_clr,"RNA","Human")
mouse_RNA_mean <- mean_df_mouse(mouse_flatten_rna_clr,"RNA","Mouse")


fin_plot <- cbind(human_TE_mean,mouse_TE_mean,human_RIBO_mean,
                  mouse_RIBO_mean,human_RNA_mean,mouse_RNA_mean)

cor_matrix <- cor(fin_plot,method="spearman")

library(corrplot)
library(RColorBrewer)
pdf("heatmap_cor_all_level.pdf",
    width = 2.4, height = 2.2)
corrplot(cor_matrix, type="upper", order="hclust",is.corr = FALSE,
         col = COL1('YlOrRd', 10),tl.cex=0.5,
         method='pie',col.lim=c(0,1))
dev.off()
